@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo": "69b62d2b5ab4c8bd663c0e94",
    "postId": "69b7925b3e49ffe96e2a1432",
    "comment": "Hello 10",
    "profilePicture": "https://res.cloudinary.com/dgneeqwxw/image/upload/v1773548869/69b63544820278448f8a2615"
}

###
GET {{baseUrl}}/{{urlPath}}/post/comments/names/699be0ffe5297ac4f9ce95df
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/699be0ffe5297ac4f9ce95df/699be5e3d503376c69da159b
Content-Type: application/json
Accept: application/json
withCredentials: true
