@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo": "699c3560c87a593145fd53b5",
    "postId": "699fcff9fe1fbb2b0b6dbd77",
    "comment": "This is my third comment",
    "profilePicture": "https://res.cloudinary.com/dgneeqwxw/image/upload/v1771587085/6998460a06cd0adfd12dffe2"
}

###
GET {{baseUrl}}/{{urlPath}}/post/comments/names/699be0ffe5297ac4f9ce95df
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/699be0ffe5297ac4f9ce95df/699be5e3d503376c69da159b
Content-Type: application/json
Accept: application/json
withCredentials: true
