@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo": "69b62d2b5ab4c8bd663c0e94",
    "postId": "69ba2630402712ed56a62cc8",
    "type": "love",
    "previousReaction": "",
    "postReactions": {"like": 0,"love": 1,"happy": 0,"angry": 0,"sad": 0,"wow": 0},
    "profilePicture": "https://res.cloudinary.com/dgneeqwxw/image/upload/v1773546796/69b62d2b5ab4c8bd663c0e94"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/69ba2630402712ed56a62cc8/love/{"like": 0,"love": 0,"happy": 0,"angry": 0,"sad": 0,"wow": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/6999adab2fffc03496acbf94
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Hhoang1204/69ba2630402712ed56a62cc8
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/hhoang1204
Content-Type: application/json
Accept: application/json
withCredentials: true


