@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "userTo": "699be0cbe5297ac4f9ce95d8",
    "postId": "699be0ffe5297ac4f9ce95df",
    "type": "happy",
    "previousReaction": "",
    "postReactions": {"like": 0,"love": 0,"happy": 1,"angry": 0,"sad": 0,"wow": 0},
    "profilePicture": "https://res.cloudinary.com/dgneeqwxw/image/upload/v1771587085/6998460a06cd0adfd12dffe2"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/69998850c2eb1da3e0e83efc/happy/{"like": 0,"love": 0,"happy": 0,"angry": 0,"sad": 0,"wow": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/6999adab2fffc03496acbf94
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Jayz1204/6999adab2fffc03496acbf94
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/jayz1204
Content-Type: application/json
Accept: application/json
withCredentials: true


